version = 1

test_patterns = ["tests/**"]

exclude_patterns = ["vendor/**"]

[[analyzers]]
name = "php"
enabled = true

[[analyzers]]
name = "secrets"
enabled = true

[[analyzers]]
name = "test-coverage"
enabled = true