version = 1

test_patterns = ["tests/**"]

exclude_patterns = [
  "vendor/**",
  "tmp/**",
  "**/cache/**"
]

[[analyzers]]
name = "php"
enabled = true

[[analyzers]]
name = "secrets"
enabled = true

[[analyzers]]
name = "test-coverage"
enabled = true

[[transformers]]
name = "php-cs-fixer"
enabled = true